function [f]=term2(u, head, vr, wr,relpx,relpy,relvx,relvy,robovx,robovy ,R,dt)
 lindelta=u(1);
 angdelta=u(2);
 f=[];
 for i=1:length(relpx)
  t=2.*dt.*(lindelta+vr).*((R.^2+(-1).*relpx(i).^2+(-1).*relpy(i).^2).*(( ...
   relvy(i)+(-1).*robovy).*cos(head+dt.*(angdelta+wr))+((-1).*relvx(i)+ ...
   robovx).*sin(head+dt.*(angdelta+wr)))+(relpy(i).*cos(head+dt.*( ...
   angdelta+wr))+(-1).*relpx(i).*sin(head+dt.*(angdelta+wr))).*(relpx(i).*( ...
   relvx(i)+(-1).*robovx+(lindelta+vr).*cos(head+dt.*(angdelta+wr)))+ ...
   relpy(i).*(relvy(i)+(-1).*robovy+(lindelta+vr).*sin(head+dt.*(angdelta+ ...
   wr)))));
  f=[f t];
 end
end